### ISSUE TITLE
Use fmtc for gamma converion

### ISSUE THREAD

**Issue by MonoS** [mawen1250/VapourSynth-script#2]
havsfunc removed gamma related function, now they are in fmtc.transfer

**Comment by mawen1250** [comment]
Fixed in https://github.com/mawen1250/VapourSynth-script/commit/8321a3af86477a2e3b83fb472f00b1fa4909dc0f

I copy the conversion functions from havsfunc-r18. Since sigmoid is involved this might be more efficient (also lazier...).

**Comment by RoyiAvital** [comment]
@mawen1250, IS this still alive?
